CREATE DATABASE IF NOT EXISTS BIFORCE_STAGING;

USE BIFORCE_STAGING;

CREATE TABLE SPARK_DATA (ROW_NUM INT, TEST_TYPE INT, RAW_SCORE DECIMAL(3, 0), SCORE DECIMAL(5, 2), TEST_PERIOD INT, TEST_CATEGORY INT, TRAINER_ID INT, BATCH_ID INT, GROUP_TYPE STRING, BATTERY_ID INT, BATTERY_STATUS INT);

INSERT OVERWRITE TABLE SPARK_DATA
SELECT ROW_NUMBER() OVER (), Q.* FROM
(SELECT
	CASE
		WHEN UPPER(CALIBER_ASSESSMENT.ASSESSMENT_TYPE) = 'VERBAL' THEN 1
		WHEN UPPER(CALIBER_ASSESSMENT.ASSESSMENT_TYPE) = 'EXAM' THEN 2
		WHEN UPPER(CALIBER_ASSESSMENT.ASSESSMENT_TYPE) = 'PROJECT' THEN 3
		WHEN UPPER(CALIBER_ASSESSMENT.ASSESSMENT_TYPE) = 'OTHER' THEN 4
		ELSE 0 END AS TYPE,
    CALIBER_ASSESSMENT.RAW_SCORE,
    CALIBER_GRADE.SCORE,
    CALIBER_ASSESSMENT.WEEK_NUMBER,
    CALIBER_ASSESSMENT.ASSESSMENT_CATEGORY,
    CALIBER_BATCH.TRAINER_ID,
    CALIBER_BATCH.BATCH_ID,
    CALIBER_BATCH.SKILL_TYPE,
    CALIBER_GRADE.TRAINEE_ID,
	CASE
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'DROPPED' THEN 0
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'EMPLOYED' THEN 1
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'TRAINING' THEN 2
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'SIGNED' THEN 3
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'CONFIRMED' THEN 4
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'MARKETING' THEN 5
		ELSE 6 END AS TRAINING_STATUS
FROM CALIBER_ASSESSMENT, CALIBER_BATCH, CALIBER_GRADE, CALIBER_TRAINEE
WHERE CALIBER_ASSESSMENT.ASSESSMENT_ID = CALIBER_GRADE.ASSESSMENT_ID
AND CALIBER_ASSESSMENT.BATCH_ID = CALIBER_BATCH.BATCH_ID
AND CALIBER_GRADE.TRAINEE_ID = CALIBER_TRAINEE.TRAINEE_ID

UNION ALL

SELECT
	CASE 
		WHEN UPPER(CALIBER_NOTE.NOTE_TYPE) = 'TRAINEE' THEN 5 
		WHEN UPPER(CALIBER_NOTE.NOTE_TYPE) = 'QC_TRAINEE' THEN 6
		WHEN UPPER(CALIBER_NOTE.NOTE_TYPE) = 'BATCH' THEN 7
		WHEN UPPER(CALIBER_NOTE.NOTE_TYPE) = 'QC_BATCH' THEN 8
		ELSE 0 END AS TYPE,
    100 AS RAW_SCORE,
    CASE
        WHEN UPPER(CALIBER_NOTE.QC_STATUS) = 'POOR' THEN 65 
        WHEN UPPER(CALIBER_NOTE.QC_STATUS) = 'AVERAGE' THEN 75
        WHEN UPPER(CALIBER_NOTE.QC_STATUS) = 'GOOD' THEN 85
        WHEN UPPER(CALIBER_NOTE.QC_STATUS) = 'SUPERSTAR' THEN 95
        ELSE 0 END AS SCORE,
    CALIBER_NOTE.WEEK_NUMBER,
    0 AS ASSESSMENT_CATEGORY,
    CALIBER_BATCH.TRAINER_ID,
    CALIBER_BATCH.BATCH_ID,
    CALIBER_BATCH.SKILL_TYPE,
    CALIBER_TRAINEE.TRAINEE_ID,
	CASE
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'DROPPED' THEN 0
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'EMPLOYED' THEN 1
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'TRAINING' THEN 2
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'SIGNED' THEN 3
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'CONFIRMED' THEN 4
		WHEN UPPER(CALIBER_TRAINEE.TRAINING_STATUS) = 'MARKETING' THEN 5
		ELSE 6 END AS TRAINING_STATUS
FROM CALIBER_NOTE, CALIBER_BATCH, CALIBER_TRAINEE
WHERE CALIBER_NOTE.TRAINEE_ID = CALIBER_TRAINEE.TRAINEE_ID
AND CALIBER_BATCH.BATCH_ID = CALIBER_TRAINEE.BATCH_ID
AND CALIBER_NOTE.QC_STATUS IS NOT NULL) Q;