--battery_group_relationship.csv
SELECT /*csv*/ 
TRAINEE_ID battery_id, 
BATCH_ID battery_group
FROM CALIBER_TRAINEE;

--battery_test.csv
SELECT /*csv*/
ASSESSMENT_ID BATTERY_TEST_ID,
RAW_SCORE,
CASE 
    WHEN UPPER(ASSESSMENT_TYPE) = 'VERBAL' 
    THEN 'VISUAL'
    WHEN UPPER(ASSESSMENT_TYPE) = 'EXAM' 
    THEN 'VOLTMETER'
    WHEN UPPER(ASSESSMENT_TYPE) = 'PROJECT' 
    THEN 'VIBRATION'
    WHEN UPPER(ASSESSMENT_TYPE) = 'OTHER' 
    THEN 'DROP'
END AS BATTERY_TEST_TYPE,
WEEK_NUMBER TEST_PERIOD,
BATCH_ID BATTERY_GROUP,
ASSESSMENT_CATEGORY TEST_CATEGORY
FROM CALIBER_ASSESSMENT;

--battery_test_grade.csv
SELECT /*csv*/
GRADE_ID VOLTAGE_ID,
DATE_RECEIVED,
SCORE,
ASSESSMENT_ID BATTERY_TEST_ID,
TRAINEE_ID BATTERY_ID
FROM CALIBER_GRADE;

--battery_note.csv
SELECT /*csv*/
NOTE_ID,
MAX_VISIBILITY,
IS_QC_FEEDBACK IS_AAA_FEEDBACK,
CASE
WHEN UPPER(QC_STATUS) = 'UNDEFINED' THEN '0'
WHEN UPPER(QC_STATUS) = 'POOR' THEN '25'
WHEN UPPER(QC_STATUS) = 'AVERAGE' THEN '50'
WHEN UPPER(QC_STATUS) = 'GOOD' THEN '75'
WHEN UPPER(QC_STATUS) = 'SUPERSTAR' THEN '100'
END AS AAA_STATUS,
CASE 
    WHEN NOTE_TYPE = 'QC_BATCH' THEN 'BANNER'
    WHEN NOTE_TYPE = 'TRAINEE' THEN 'MEMO'
    WHEN NOTE_TYPE = 'QC_TRAINEE' THEN 'PAMPHLET'
    WHEN NOTE_TYPE = 'BATCH' THEN 'LETTER'
END AS NOTE_TYPE,
WEEK_NUMBER TEST_PERIOD,
BATCH_ID BATTERY_GROUP,
TRAINEE_ID BATTERY_ID
FROM CALIBER_NOTE;

--battery_status => caliber_trainee
SELECT /*csv*/
TRAINEE_ID BATTERY_ID,
CASE
    WHEN UPPER(TRAINING_STATUS) = 'DROPPED' THEN 'FAILED'
    WHEN UPPER(TRAINING_STATUS) = 'TRAINING' THEN 'OTHER'
    WHEN UPPER(TRAINING_STATUS) = 'SIGNED' THEN 'SOLD'
    WHEN UPPER(TRAINING_STATUS) = 'CONFIRMED' THEN 'SHIPPED'
    WHEN UPPER(TRAINING_STATUS) = 'MARKETING' THEN 'STORE'
    WHEN UPPER(TRAINING_STATUS) = 'EMPLOYED' THEN 'PASSED'
END AS BATTERY_STATUS
FROM CALIBER_TRAINEE;
