-- TO CREATE CALIBER 2 SCHEMA ON OLTP SIDE
-- RUN COMMANDS ON A SQL IDE: ORACLE_SQL_DEVELOPER
-- THEN RUN SqoopExport_OozieWorkflow.xml
-- TO MIGRATE ALL DATA
-- ASK SYSTEM ADMIN FOR ANY CREDENTTIALS


--ORACLE CREATE TABLE ASSESSMENT COMMAND
CREATE TABLE ASSOCIATE.CALIBER2_ASSESSMENT
(ASSESSMENT_ID NUMBER(19),
RAW_SCORE NUMBER(10),
ASSESSMENT_TITLE VARCHAR2(255 CHAR),
ASSESSMENT_TYPE VARCHAR2(255 CHAR),
WEEK_NUMBER NUMBER(5),
BATCH_ID NUMBER(10),
ASSESSMENT_CATEGORY NUMBER(10)
);




--ORACLE CREATE TABLE CATEGORY COMMAND
CREATE TABLE ASSOCIATE.CALIBER2_CATEGORY
(CATEGORY_ID NUMBER(10),
SKILL_CATEGORY VARCHAR2(255 CHAR),
IS_ACTIVE NUMBER(1)
);




--ORACLE CREATE TABLE BATCH COMMAND
CREATE TABLE ASSOCIATE.CALIBER2_BATCH
(BATCH_ID NUMBER(10) NOT NULL,
BORDERLINE_GRADE_THRESHOLD NUMBER(5),
END_DATE TIMESTAMP NOT NULL,
GOOD_GRADE_THRESHOLD NUMBER(5),
LOCATION VARCHAR2(255 CHAR) NOT NULL,
SKILL_TYPE VARCHAR2(255 CHAR),
START_DATE TIMESTAMP NOT NULL,
TRAINGING_NAME VARCHAR2(255 CHAR),
TRAINING_TYPE VARCHAR2(255 CHAR),
NUMBER_OF_WEEKS NUMBER(10) NOT NULL,
CO_TRAINER_ID NUMBER(10),
TRAINER_ID NUMBER(10) NOT NULL,
RESOURCE_ID VARCHAR2(255 CHAR),
ADDRESS_ID NUMBER(10),
GRADED_WEEKS NUMBER(10)
);




--ORACLE CREATE TABLE COMMAND FOR ADDRESS TABLE
CREATE TABLE ASSOCIATE.CALIBER2_ADDRESS
( ADDRESS_ID NUMBER(10) NOT NULL,
ADDRESS_STREET VARCHAR2(255 CHAR),
ADDRESS_CITY VARCHAR2(63 CHAR),
ADDRESS_STATE VARCHAR2(2 CHAR),
ADDRESS_ZIPCODE VARCHAR2(15 CHAR),
ADDRESS_COMPANY VARCHAR2(255 CHAR),
ACTIVE NUMBER(1) NOT NULL
);




--ORACLE CREATE TABLE COMMAND FOR TRAINER TABLE
CREATE TABLE ASSOCIATE.CALIBER2_TRAINER
(TRAINER_ID NUMBER(10) NOT NULL,
EMAIL VARCHAR2(255 CHAR) NOT NULL,
NAME VARCHAR2(255 CHAR) NOT NULL,
TIER VARCHAR2(255 CHAR),
TITLE VARCHAR2(255 CHAR) NOT NULL
);




--ORACLE CREATE TABLE COMMAND FOR GRADE TABLE
CREATE TABLE ASSOCIATE.CALIBER2_GRADE
(GRADE_ID NUMBER(19) NOT NULL,
DATE_RECEIVED TIMESTAMP(6) NOT NULL,
SCORE FLOAT(126) NOT NULL,
ASSESSMENT_ID NUMBER(19) NOT NULL,
ASSIGNMENT_ID NUMBER(19) NOT NULL
);




--ORACLE CREATE TABLE COMMAND FOR TRAINEE NOTE
CREATE TABLE ASSOCIATE.CALIBER2_TRAINEE_NOTE
(NOTE_ID NUMBER(10) NOT NULL,
NOTE_CONTENT VARCHAR2(4000 CHAR),
MAX_VISIBILITY NUMBER(10),
IS_QC_FEEDBACK NUMBER(1),
QC_STATUS VARCHAR2(255 CHAR),
NOTE_TYPE VARCHAR2(255 CHAR),
WEEK_NUMBER NUMBER(5),
ASSIGNMENT_ID NUMBER(19)
);




--ORACLE CREATE TABLE COMMAND FOR BATCH NOTE
CREATE TABLE ASSOCIATE.CALIBER2_BATCH_NOTE
(NOTE_ID NUMBER(10) NOT NULL,
NOTE_CONTENT VARCHAR2(4000 CHAR),
MAX_VISIBILITY NUMBER(10),
IS_QC_FEEDBACK NUMBER(1) NOT NULL,
QC_STATUS VARCHAR2(255 CHAR),
NOTE_TYPE VARCHAR2(255 CHAR),
WEEK_NUMBER NUMBER(5),
BATCH_ID NUMBER(10)
);




--ORACLE CREATE TABLE COMMAND FOR ASSIGNMENT TABLE
CREATE TABLE ASSOCIATE.CALIBER2_ASSIGNMENT
(ASSINGMENT_ID NUMBER(19) NOT NULL,
TRAINEE_ID NUMBER(10) NOT NULL,
BATCH_ID NUMBER(10) NOT NULL
);




--ORACLE CREATE TABLE COMMAND FOR TRAINEE TABLE
CREATE TABLE ASSOCIATE.CALIBER2_TRAINEE
(TRAINEE_ID NUMBER(10) NOT NULL,
TRAINEE_EMAIL VARCHAR2(255 CHAR),
TRAINEE_NAME VARCHAR2(255 CHAR),
TRAINING_STATUS VARCHAR2(255 CHAR),
PHONE_NUMBER VARCHAR2(255 CHAR),
PROFILE_URL VARCHAR2(255 CHAR),
SKYPE_ID VARCHAR2(255 CHAR),
RESOURCE_ID VARCHAR2(255 CHAR),
FLAG_NOTES VARCHAR2(400 CHAR),
FLAG_STATUS VARCHAR2(255 CHAR),
TECH_SCREEN_SCORE NUMBER(10,2),
RECRUITER_NAME VARCHAR2(255 CHAR),
COLLEGE VARCHAR(255 CHAR),
DEGREE VARCHAR2(255 CHAR),
MAJOR VARCHAR2(255 CHAR),
TECH_SCREENER_NAME VARCHAR(255 CHAR),
REVPRO_PROJECT_COMPLETION NUMBER(10)
);




--ADD PRIMARY KEYS TO TABLES
ALTER TABLE ASSOCIATE.CALIBER2_ASSESSMENT ADD PRIMARY KEY (ASSESSMENT_ID);
ALTER TABLE ASSOCIATE.CALIBER2_TRAINEE ADD PRIMARY KEY (TRAINEE_ID);
--ALTER TABLE ASSOCIATE.CALIBER2_PANEL ADD PRIMARY KEY (PANEL_ID);
ALTER TABLE ASSOCIATE.CALIBER2_CATEGORY ADD PRIMARY KEY ("CATEGORY_ID");
ALTER TABLE ASSOCIATE."CALIBER2_BATCH" ADD PRIMARY KEY ("BATCH_ID");
ALTER TABLE ASSOCIATE.CALIBER2_TRAINER ADD PRIMARY KEY ("TRAINER_ID");
ALTER TABLE ASSOCIATE.CALIBER2_TRAINER ADD PRIMARY KEY ("TRAINER_ID");
ALTER TABLE ASSOCIATE.CALIBER2_ADDRESS ADD PRIMARY KEY (ADDRESS_ID);
ALTER TABLE CALIBER2_GRADE ADD PRIMARY KEY (GRADE_ID);
--ALTER TABLE ASSOCIATE.caliber2_panel ADD CHECK (PANEL_ROUND>=1);


--ADD FK RELATIONSHIP BETWEEN TRAINEE_ID COLUMNS IN PANEL TABLE AND --TRAINEE TABLE
--ALTER TABLE ASSOCIATE.CALIBER2_PANEL ADD CONSTRAINT --"FK_JFR6OCW09DW69AAIGW4U7QRP5" FOREIGN KEY ("TRAINEE_ID") --REFERENCES ASSOCIATE.CALIBER2_TRAINEE (TRAINEE_ID) ENABLE;
         


--ALTER TABLE "ASSOCIATE"."CALIBER2_PANEL" ADD CONSTRAINT --"FK_QBCLCSTJGHPAYHWIAGX8HVX4V" FOREIGN KEY ("PANELIST_ID") --REFERENCES "ASSOCIATE"."CALIBER2_TRAINER" ("TRAINER_ID") ENABLE;


--ALTER TABLE ASSOCIATE.CALIBER2_PANEL_FEEDBACK ADD CONSTRAINT --"FK_DUQ9ETOU1QMJBNMD0D43NX0TC" FOREIGN KEY (CATEGORY_ID) --REFERENCES ASSOCIATE.CALIBER2_CATEGORY (CATEGORY_ID) ENABLE;


--ALTER TABLE ASSOCIATE."CALIBER2_PANEL_FEEDBACK" ADD CONSTRAINT --"FK_GQXJIXAFOY11XR6L8BMPSTV0D" FOREIGN KEY ("PANEL_ID") REFERENCES --ASSOCIATE."CALIBER2_PANEL" ("PANEL_ID") ENABLE;
          
ALTER TABLE ASSOCIATE.CALIBER2_BATCH ADD CONSTRAINT "FK_35QJTOMOM338V680F3XKO7PLH" FOREIGN KEY ("TRAINER_ID") 
REFERENCES "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") ENABLE;
 
ALTER TABLE ASSOCIATE."CALIBER2_BATCH" ADD CONSTRAINT "FK_35QJTOMOM338V680F3XKO7PLH" FOREIGN KEY ("TRAINER_ID")
REFERENCES ASSOCIATE."CALIBER2_TRAINER" ("TRAINER_ID") ENABLE;


ALTER TABLE ASSOCIATE."CALIBER2_BATCH" ADD CONSTRAINT
"FK_4IDDE4FODT9VMU6CIXCQ4S2P1" FOREIGN KEY ("CO_TRAINER_ID")
REFERENCES ASSOCIATE."CALIBER2_TRAINER" ("TRAINER_ID") ENABLE;


ALTER TABLE ASSOCIATE."CALIBER2_BATCH" ADD CONSTRAINT
"FK_BATCH_ADDRESS" FOREIGN KEY ("ADDRESS_ID")
REFERENCES ASSOCIATE."CALIBER2_ADDRESS" ("ADDRESS_ID") ENABLE;
 
ALTER TABLE CALIBER2_BATCH_NOTE ADD PRIMARY KEY (NOTE_ID); 
ALTER TABLE CALIBER2_TRAINEE_NOTE ADD PRIMARY KEY (NOTE_ID);


ALTER TABLE CALIBER2_BATCH_NOTE ADD FOREIGN KEY("BATCH_ID") REFERENCES CALIBER2_BATCH("BATCH_ID") ENABLE;


--ASSIGNMENT TABLE ALTERATIONS
ALTER TABLE "CALIBER2_ASSIGNMENT" ADD PRIMARY KEY ("ASSINGMENT_ID");


ALTER TABLE "CALIBER2_ASSIGNMENT" ADD FOREIGN KEY ("TRAINEE_ID") REFERENCES CALIBER2_TRAINEE ("TRAINEE_ID") ENABLE;


ALTER TABLE "CALIBER2_ASSIGNMENT" ADD FOREIGN KEY ("BATCH_ID") REFERENCES CALIBER2_BATCH ("BATCH_ID") ENABLE;


ALTER TABLE "CALIBER2_ASSIGNMENT" ADD FOREIGN KEY ("TRAINEE_ID") REFERENCES CALIBER2_TRAINEE ("TRAINEE_ID") ENABLE;
--------------------------------------


--GRADE TABLE ALTERATIONS
ALTER TABLE "CALIBER2_GRADE" ADD FOREIGN KEY ("ASSIGNMENT_ID") REFERENCES CALIBER2_ASSIGNMENT ("ASSINGMENT_ID") ENABLE;
--------------------------------------


--BATCH TABLE ALTERATIONS
ALTER TABLE "CALIBER2_BATCH" ADD PRIMARY KEY ("BATCH_ID");
-------------------------------------


COMMIT;